# Generated by Django 4.1.5 on 2023-04-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
