# Generated by Django 4.1.5 on 2023-04-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_slug_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
