# Generated by Django 4.1.5 on 2023-04-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_category_slug_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='small_description',
            field=models.TextField(max_length=1000),
        ),
    ]
