# Generated by Django 4.1.5 on 2023-04-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='trending',
        ),
    ]
