# Generated by Django 4.1.5 on 2023-04-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_category_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_description',
        ),
    ]
