# Generated by Django 4.1.5 on 2023-04-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
