# Generated by Django 4.1.5 on 2023-04-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_orderitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
